### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-microprofile-istio-retry-fallback#10]
1. In server.xml, why do you need mpMetrics feature?
2. since you are using mpConfig, 
private final String SYS_HTTP_PORT = System.getProperty("system.http.port");
should use MP Config to inject.
3. Why don't you inject the rest client via `@Inject @RestClient`

**Comment by gkwan-ibm** [comment]
- 1. was addressed
- 2. was addressed
- 3. The reason is that the inventory service is not only deal with one system service, instead the inventory service is required to invoke the system service on different hosts.
