### ISSUE TITLE
Update to use MP FT 3.0

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-microprofile-istio-retry-fallback#68]

**Comment by gkwan-ibm** [comment]
@Emily-Jiang 
Beside only update the pom.xml and server.xml to latest versions, what do you expect to change in this guide?

**Comment by gkwan-ibm** [comment]
Based on https://github.com/OpenLiberty/guides-common/issues/555#issue-754605505, just need to update the pom.xml and server.xml to latest versions

**Comment by gkwan-ibm** [comment]
close
- the [guide](https://openliberty.io/guides/microprofile-istio-retry-fallback.html) was updated
